"""Compare a supplier country with the country strings stored on a list entry.

Two-letter codes pass through. OFAC-style English names map to the same codes.
A value we cannot read does not count as a contradiction.
"""

from __future__ import annotations

_NAMES = {
    "afghanistan": "AF",
    "albania": "AL",
    "algeria": "DZ",
    "angola": "AO",
    "antigua and barbuda": "AG",
    "argentina": "AR",
    "armenia": "AM",
    "aruba": "AW",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahamas, the": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bolivia": "BO",
    "bosnia and herzegovina": "BA",
    "brazil": "BR",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burma": "MM",
    "myanmar": "MM",
    "cabo verde": "CV",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "cayman islands": "KY",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "colombia": "CO",
    "comoros": "KM",
    "congo, democratic republic of the": "CD",
    "congo, republic of the": "CG",
    "costa rica": "CR",
    "cote d ivoire": "CI",
    "cote d'ivoire": "CI",
    "croatia": "HR",
    "cuba": "CU",
    "curacao": "CW",
    "cyprus": "CY",
    "czech republic": "CZ",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominica": "DM",
    "dominican republic": "DO",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "estonia": "EE",
    "ethiopia": "ET",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "georgia": "GE",
    "germany": "DE",
    "ghana": "GH",
    "gibraltar": "GI",
    "greece": "GR",
    "guatemala": "GT",
    "guernsey": "GG",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "honduras": "HN",
    "hong kong": "HK",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "jamaica": "JM",
    "japan": "JP",
    "jersey": "JE",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "korea, north": "KP",
    "north korea": "KP",
    "korea, south": "KR",
    "south korea": "KR",
    "kosovo": "XK",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "laos": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "macau": "MO",
    "macao": "MO",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "man, isle of": "IM",
    "marshall islands": "MH",
    "mauritania": "MR",
    "mauritius": "MU",
    "mexico": "MX",
    "moldova": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "morocco": "MA",
    "mozambique": "MZ",
    "namibia": "NA",
    "netherlands": "NL",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "north macedonia, the republic of": "MK",
    "norway": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palau": "PW",
    "palestinian": "PS",
    "panama": "PA",
    "paraguay": "PY",
    "peru": "PE",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "qatar": "QA",
    "romania": "RO",
    "russia": "RU",
    "russian federation": "RU",
    "rwanda": "RW",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint vincent and the grenadines": "VC",
    "samoa": "WS",
    "san marino": "SM",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "slovakia": "SK",
    "slovenia": "SI",
    "somalia": "SO",
    "south africa": "ZA",
    "south sudan": "SS",
    "spain": "ES",
    "sri lanka": "LK",
    "sudan": "SD",
    "suriname": "SR",
    "sweden": "SE",
    "switzerland": "CH",
    "syria": "SY",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "thailand": "TH",
    "the gambia": "GM",
    "togo": "TG",
    "trinidad and tobago": "TT",
    "tunisia": "TN",
    "turkey": "TR",
    "turkiye": "TR",
    "türkiye": "TR",
    "turkmenistan": "TM",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    "united states": "US",
    "united states of america": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "venezuela": "VE",
    "vietnam": "VN",
    "viet nam": "VN",
    "virgin islands, british": "VG",
    "west bank": "PS",
    "yemen": "YE",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    "region: russia": "RU",
    "region: iran": "IR",
    "region: crimea": "UA",
    "region: northern mali": "ML",
    "region: gaza": "PS",
    "region: north gaza": "PS",
    "region: northern gaza": "PS",
    "region: west bank": "PS",
    "ua-dpr": "UA",
    "ua-lpr": "UA",
}


def country_codes(value: str) -> set[str]:
    text = " ".join(value.split())
    if len(text) == 2 and text.isalpha():
        return {text.upper()}
    code = _NAMES.get(text.casefold())
    return {code} if code else set()


def country_relation(supplier_country: str, listed_countries: list[str]) -> tuple[bool, bool]:
    """Return (agrees, contradicts).

    Agreement includes a list entry with no readable country. Contradiction
    requires both sides to have codes and no overlap.
    """

    supplier = country_codes(supplier_country)
    listed: set[str] = set()
    for value in listed_countries:
        listed |= country_codes(value)
    agrees = not listed or bool(supplier & listed)
    contradicts = bool(supplier) and bool(listed) and not (supplier & listed)
    return agrees, contradicts
